package br.com.confirmacao.session.application;
import br.com.confirmacao.patient.application.PatientNotFoundException;import br.com.confirmacao.patient.infrastructure.PatientRepository;import br.com.confirmacao.professional.application.ProfessionalNotFoundException;import br.com.confirmacao.professional.infrastructure.ProfessionalRepository;import br.com.confirmacao.session.domain.*;import br.com.confirmacao.session.infrastructure.SessionAppointmentRepository;import org.springframework.data.domain.Page;import org.springframework.data.domain.Pageable;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service public class SessionAppointmentService{private final SessionAppointmentRepository sessions;private final PatientRepository patients;private final ProfessionalRepository professionals;public SessionAppointmentService(SessionAppointmentRepository s,PatientRepository p,ProfessionalRepository r){sessions=s;patients=p;professionals=r;}
 @Transactional(readOnly=true)public List<SessionAppointment> find(UUID professionalId,Instant start,Instant end){if(start==null||end==null||!end.isAfter(start))throw new IllegalArgumentException("Período de consulta inválido");return sessions.findAllByProfessionalIdAndStartsAtLessThanAndEndsAtGreaterThanOrderByStartsAtAsc(professionalId,end,start);}
 @Transactional(readOnly=true)public Page<SessionAppointment> findByPatient(UUID professionalId,UUID patientId,Pageable pageable){patients.findByIdAndProfessionalId(patientId,professionalId).orElseThrow(()->new PatientNotFoundException(patientId));return sessions.findAllByProfessionalIdAndPatientId(professionalId,patientId,pageable);}
 @Transactional public SessionAppointment create(UUID professionalId,UUID patientId,Instant start,Instant end,SessionModality modality,String link,String notes){future(start);var professional=professionals.findById(professionalId).orElseThrow(()->new ProfessionalNotFoundException(professionalId));var patient=patients.findByIdAndProfessionalId(patientId,professionalId).filter(x->x.isActive()).orElseThrow(()->new PatientNotFoundException(patientId));available(professionalId,start,end,null);return sessions.save(new SessionAppointment(professional,patient,start,end,modality,link,notes));}
 @Transactional public SessionAppointment update(UUID professionalId,UUID id,UUID patientId,Instant start,Instant end,SessionModality modality,SessionStatus status,String link,String notes){var appointment=find(professionalId,id);if(!appointment.getEndsAt().isAfter(Instant.now())||terminal(appointment.getStatus()))throw new IllegalArgumentException("Sessões encerradas estão disponíveis somente para consulta");if(status!=SessionStatus.SCHEDULED&&status!=SessionStatus.CONFIRMED&&status!=SessionStatus.CANCELED)throw new IllegalArgumentException("O resultado só pode ser informado após o término da sessão");var patient=patients.findByIdAndProfessionalId(patientId,professionalId).filter(x->x.isActive()).orElseThrow(()->new PatientNotFoundException(patientId));if(status!=SessionStatus.CANCELED){future(start);available(professionalId,start,end,id);}appointment.update(patient,start,end,modality,status,link,notes);return appointment;}
 @Transactional public SessionAppointment updateResult(UUID professionalId,UUID id,SessionStatus status,String notes){var appointment=find(professionalId,id);if(appointment.getEndsAt().isAfter(Instant.now()))throw new IllegalArgumentException("O resultado só pode ser informado após o término da sessão");appointment.updateResult(status,notes);return appointment;}
 private SessionAppointment find(UUID professionalId,UUID id){return sessions.findByIdAndProfessionalId(id,professionalId).orElseThrow(()->new SessionNotFoundException(id));}
 private boolean terminal(SessionStatus status){return status==SessionStatus.COMPLETED||status==SessionStatus.CANCELED||status==SessionStatus.NO_SHOW;}
 private void future(Instant start){if(start==null||start.isBefore(Instant.now()))throw new IllegalArgumentException("Não é possível agendar uma sessão em um horário que já passou");}
 private void available(UUID professionalId,Instant start,Instant end,UUID ignored){if(start==null||end==null||!end.isAfter(start))throw new IllegalArgumentException("O horário final deve ser posterior ao inicial");boolean conflict=ignored==null?sessions.existsByProfessionalIdAndStatusNotAndStartsAtLessThanAndEndsAtGreaterThan(professionalId,SessionStatus.CANCELED,end,start):sessions.existsByProfessionalIdAndStatusNotAndStartsAtLessThanAndEndsAtGreaterThanAndIdNot(professionalId,SessionStatus.CANCELED,end,start,ignored);if(conflict)throw new SessionConflictException();}
}
