spring:
  datasource:
    url: ${HOMOLOG_DATASOURCE_URL:jdbc:postgresql://localhost:5432/confirmacao_consultas?currentSchema=confirmacao_homolog_app}
    username: ${HOMOLOG_DATASOURCE_USERNAME:confirmacao_app}
    password: ${HOMOLOG_DATASOURCE_PASSWORD:321321321}
  jpa:
    properties:
      hibernate:
        default_schema: confirmacao_homolog_app
  flyway:
    schemas: confirmacao_homolog_app
    default-schema: confirmacao_homolog_app
    create-schemas: true

server:
  port: 8081

app:
  homolog:
    seed: ${HOMOLOG_SEED:true}
  whatsapp:
    provider: simulated
  password-reset:
    frontend-url: http://127.0.0.1:4173
  security:
    cors:
      allowed-origins: http://localhost:5173,http://127.0.0.1:5173,http://localhost:4173,http://127.0.0.1:4173
    jwt:
      secret: ${HOMOLOG_JWT_SECRET:SG9tb2xvZ2FjYW9Db25maXJtYVNlZ3JlZG9Mb2NhbDIwMjY=}
      issuer: http://localhost:8081
