package br.com.confirmacao;
import br.com.confirmacao.auth.application.*;import br.com.confirmacao.patient.application.*;import br.com.confirmacao.patient.domain.*;import br.com.confirmacao.patient.infrastructure.PatientRepository;import br.com.confirmacao.professional.access.ProfessionalAccessService;import br.com.confirmacao.professional.application.ProfessionalService;import br.com.confirmacao.professional.domain.Professional;import br.com.confirmacao.professional.infrastructure.ProfessionalRepository;import br.com.confirmacao.user.domain.*;import br.com.confirmacao.user.infrastructure.UserRepository;import org.junit.jupiter.api.Test;import org.springframework.data.domain.Pageable;import org.springframework.security.crypto.password.PasswordEncoder;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;
class IndividualProfessionalModelTest{
 @Test void rolesAreOnlyAdminAndProfessional(){assertArrayEquals(new UserRole[]{UserRole.ADMIN,UserRole.PROFESSIONAL},UserRole.values());}
 @Test void professionalUserRequiresProfessional(){assertThrows(IllegalArgumentException.class,()->new User(null,"Nome","a@b.com","hash",UserRole.PROFESSIONAL));assertDoesNotThrow(()->User.globalAdmin("Admin","admin@x.com","hash"));}
 @Test void patientBelongsToProfessional(){var p=new Professional("Ana","ana@x.com",null,null);var patient=new Patient(p,"João",null,"11999999999",null,PreferredContactChannel.WHATSAPP);assertSame(p,patient.getProfessional());}
 @Test void patientLookupIsScopedToAuthenticatedProfessional(){var patients=mock(PatientRepository.class);var pros=mock(ProfessionalRepository.class);var service=new PatientService(patients,pros);UUID professional=UUID.randomUUID(),otherPatient=UUID.randomUUID();when(patients.findByIdAndProfessionalId(otherPatient,professional)).thenReturn(Optional.empty());assertThrows(PatientNotFoundException.class,()->service.findById(professional,otherPatient));verify(patients).findByIdAndProfessionalId(otherPatient,professional);}
 @Test void loginUsesGlobalEmail(){var users=mock(UserRepository.class);var encoder=mock(PasswordEncoder.class);var tokens=mock(TokenService.class);var admin=User.globalAdmin("Admin","admin@x.com","hash");when(users.findByEmailIgnoreCase("admin@x.com")).thenReturn(Optional.of(admin));when(encoder.matches("senha","hash")).thenReturn(true);when(tokens.generate(admin)).thenReturn("jwt");when(tokens.expirationSeconds()).thenReturn(10L);var result=new AuthService(users,encoder,tokens).authenticate(" ADMIN@X.COM ","senha");assertEquals("jwt",result.accessToken());verify(users).findByEmailIgnoreCase("admin@x.com");}
}
