package br.com.confirmacao;
import br.com.confirmacao.auth.application.*;import br.com.confirmacao.audit.application.AuditService;import br.com.confirmacao.audit.domain.AuditAction;import br.com.confirmacao.audit.infrastructure.AuditLogRepository;import br.com.confirmacao.patient.application.*;import br.com.confirmacao.patient.domain.*;import br.com.confirmacao.patient.infrastructure.PatientRepository;import br.com.confirmacao.professional.access.ProfessionalAccessService;import br.com.confirmacao.professional.application.ProfessionalService;import br.com.confirmacao.professional.domain.Professional;import br.com.confirmacao.professional.infrastructure.ProfessionalRepository;import br.com.confirmacao.user.domain.*;import br.com.confirmacao.user.infrastructure.UserRepository;import org.junit.jupiter.api.Test;import org.springframework.data.domain.Pageable;import org.springframework.security.crypto.password.PasswordEncoder;import java.time.Instant;import java.util.*;import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
class IndividualProfessionalModelTest{
 @Test void rolesAreOnlyAdminAndProfessional(){assertArrayEquals(new UserRole[]{UserRole.ADMIN,UserRole.PROFESSIONAL},UserRole.values());}
 @Test void professionalUserRequiresProfessional(){assertThrows(IllegalArgumentException.class,()->new User(null,"Nome","a@b.com","hash",UserRole.PROFESSIONAL));assertDoesNotThrow(()->User.globalAdmin("Admin","admin@x.com","hash"));}
 @Test void patientBelongsToProfessional(){var p=new Professional("Ana","ana@x.com",null,null);var patient=new Patient(p,"João",null,"11999999999",null,PreferredContactChannel.WHATSAPP);assertSame(p,patient.getProfessional());}
 @Test void inactivePatientMustBeActivatedBeforeChanges(){var professional=new Professional("Ana","ana@x.com",null,null);var patient=new Patient(professional,"João",null,"11999999999",null,PreferredContactChannel.WHATSAPP);patient.deactivate();assertThrows(IllegalArgumentException.class,()->patient.update("João Silva",null,"11988888888",null,PreferredContactChannel.WHATSAPP));assertThrows(IllegalArgumentException.class,patient::grantConsent);assertThrows(IllegalArgumentException.class,patient::revokeConsent);patient.activate();assertDoesNotThrow(()->patient.update("João Silva",null,"11988888888",null,PreferredContactChannel.WHATSAPP));}
 @Test void patientLookupIsScopedToAuthenticatedProfessional(){var patients=mock(PatientRepository.class);var pros=mock(ProfessionalRepository.class);var service=new PatientService(patients,pros,mock(br.com.confirmacao.session.infrastructure.SessionAppointmentRepository.class));UUID professional=UUID.randomUUID(),otherPatient=UUID.randomUUID();when(patients.findByIdAndProfessionalId(otherPatient,professional)).thenReturn(Optional.empty());assertThrows(PatientNotFoundException.class,()->service.findById(professional,otherPatient));verify(patients).findByIdAndProfessionalId(otherPatient,professional);}
 @Test void loginUsesGlobalEmail(){var users=mock(UserRepository.class);var encoder=mock(PasswordEncoder.class);var tokens=mock(TokenService.class);var admin=User.globalAdmin("Admin","admin@x.com","hash");when(users.findByEmailIgnoreCase("admin@x.com")).thenReturn(Optional.of(admin));when(encoder.matches("senha","hash")).thenReturn(true);when(tokens.generate(admin)).thenReturn("jwt");when(tokens.expirationSeconds()).thenReturn(10L);var result=new AuthService(users,encoder,tokens).authenticate(" ADMIN@X.COM ","senha");assertEquals("jwt",result.accessToken());verify(users).findByEmailIgnoreCase("admin@x.com");}
 @Test void authenticatedUserCanChangePassword(){var users=mock(UserRepository.class);var encoder=mock(PasswordEncoder.class);var user=User.globalAdmin("Admin","admin@x.com","hash-antigo");when(users.findById(user.getId())).thenReturn(Optional.of(user));when(encoder.matches("SenhaAtual1","hash-antigo")).thenReturn(true);when(encoder.matches("NovaSenha1","hash-antigo")).thenReturn(false);when(encoder.encode("NovaSenha1")).thenReturn("hash-novo");new PasswordChangeService(users,encoder).change(user.getId(),"SenhaAtual1","NovaSenha1");assertEquals("hash-novo",user.getPasswordHash());}
 @Test void auditCountsLoginFailuresFromLastSevenDays(){var repository=mock(AuditLogRepository.class);when(repository.countByActionAndCreatedAtGreaterThanEqual(eq(AuditAction.LOGIN_FAILURE),any(Instant.class))).thenReturn(6L);assertEquals(6L,new AuditService(repository).loginFailuresLast7Days());}
}
