package br.com.confirmacao.audit.domain;

public enum AuditAction {
    LOGIN_SUCCESS, LOGIN_FAILURE,
    TENANT_CREATED, TENANT_UPDATED, TENANT_ACTIVATED, TENANT_DEACTIVATED,
    PROFESSIONAL_CREATED, PROFESSIONAL_UPDATED,
    PROFESSIONAL_ACTIVATED, PROFESSIONAL_DEACTIVATED
}
