package br.com.confirmacao.audit.domain;

public enum AuditAction {
    LOGIN_SUCCESS, LOGIN_FAILURE,
    TENANT_CREATED, TENANT_UPDATED, TENANT_ACTIVATED, TENANT_DEACTIVATED,
    PROFESSIONAL_CREATED, PROFESSIONAL_UPDATED,
    PROFESSIONAL_ACTIVATED, PROFESSIONAL_DEACTIVATED,
    PATIENT_CREATED, PATIENT_UPDATED, PATIENT_ACTIVATED, PATIENT_DEACTIVATED,
    PATIENT_CONSENT_GRANTED, PATIENT_CONSENT_REVOKED,
    PASSWORD_RESET_REQUESTED, PASSWORD_RESET_COMPLETED
}
