package br.com.confirmacao.session.api;
import br.com.confirmacao.audit.application.AuditService;import br.com.confirmacao.audit.domain.AuditAction;import br.com.confirmacao.session.application.SessionAppointmentService;import br.com.confirmacao.session.domain.SessionStatus;import br.com.confirmacao.shared.api.PageResponse;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.Valid;import org.springdoc.core.annotations.ParameterObject;import org.springframework.data.domain.Pageable;import org.springframework.data.domain.Sort;import org.springframework.data.web.PageableDefault;import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;import org.springframework.web.bind.annotation.*;import java.time.Instant;import java.util.*;
@RestController @RequestMapping("/api/v1/sessions") public class SessionController{private final SessionAppointmentService service;private final AuditService audit;public SessionController(SessionAppointmentService s,AuditService a){service=s;audit=a;}
 @GetMapping public List<SessionResponse> all(JwtAuthenticationToken jwt,@RequestParam Instant start,@RequestParam Instant end){return service.find(pid(jwt),start,end).stream().map(SessionResponse::from).toList();}
 @GetMapping("/patient/{patientId}")public PageResponse<SessionResponse> byPatient(JwtAuthenticationToken jwt,@PathVariable UUID patientId,@ParameterObject@PageableDefault(size=50,sort="startsAt",direction=Sort.Direction.DESC)Pageable pageable){return PageResponse.from(service.findByPatient(pid(jwt),patientId,pageable).map(SessionResponse::from));}
 @PostMapping public SessionResponse create(JwtAuthenticationToken jwt,@Valid@RequestBody SessionRequest r,HttpServletRequest h){var x=service.create(pid(jwt),r.patientId(),r.startsAt(),r.endsAt(),r.modality(),r.meetingLink(),r.notes());audit.record(AuditAction.SESSION_CREATED,"SESSION",x.getId(),h);return SessionResponse.from(x);}
 @PutMapping("/{id}")public SessionResponse update(JwtAuthenticationToken jwt,@PathVariable UUID id,@Valid@RequestBody SessionRequest r,HttpServletRequest h){var x=service.update(pid(jwt),id,r.patientId(),r.startsAt(),r.endsAt(),r.modality(),r.status()==null?SessionStatus.SCHEDULED:r.status(),r.meetingLink(),r.notes());audit.record(AuditAction.SESSION_UPDATED,"SESSION",id,h);return SessionResponse.from(x);}
 @PatchMapping("/{id}/result")public SessionResponse updateResult(JwtAuthenticationToken jwt,@PathVariable UUID id,@Valid@RequestBody SessionResultRequest r,HttpServletRequest h){var x=service.updateResult(pid(jwt),id,r.status(),r.notes());audit.record(AuditAction.SESSION_UPDATED,"SESSION",id,h);return SessionResponse.from(x);}
 private UUID pid(JwtAuthenticationToken j){return UUID.fromString(j.getToken().getClaimAsString("professional_id"));}
}
